apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
stringData:
  client_id: kuc95RbkaP11CNTRL
  client_secret: tskey-client-kuc95RbkaP11CNTRL-N1SfevHDh979MmRqGjFeA7LVvPU7rQjrS