apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster4-raj-eks
  region: us-east-1
  version: "1.29"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
addons:
  - name: coredns 