apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: default
  labels:
    app: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - image: nicolaka/netshoot
        command:
          - sleep
          - infinity
        imagePullPolicy: IfNotPresent
        name: netshoot
      restartPolicy: Always
