---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 30m
  path: ./clusters/common/flux/repositories/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: dogfooding-tailscale
