apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster2-raj-eks
  region: us-east-1
  version: "1.29"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
addons:
  - name: coredns

managedNodeGroups:
  - name: ng-cluster2
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3