configs:
  cm:
    resource.ignoreResourceUpdatesEnabled: "false"
    exec.enabled: "true"
    kustomize.buildOptions: --enable-helm
  params:
    controller.repo.server.timeout.seconds: "300"
    server.repo.server.timeout.seconds: "300"
  repositories:
    argoproj-helm:
      type: helm
      name: argo-cd
      url: https://argoproj.github.io/argo-helm
server:
  env:
    - name: ARGOCD_GRPC_KEEP_ALIVE_MIN
      value: "30s"
  extraArgs:
    - --request-timeout=300s
    - --insecure
    - --repo-server-timeout-seconds=300
  resources:
    # requests:
    #   cpu: 500m
    #   memory: 256Mi
    limits:
      memory: 256Mi

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 128Mi

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  # resources:
  #   requests:
  #     cpu: 1
  #     memory: 1Gi
    limits:
      memory: 1Gi

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 128Mi

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 512Mi
    limits:
      memory: 512Mi
