apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster3-raj
  region: us-east-1
  version: "1.29"

# kubernetesNetworkConfig:  
#   ipFamily: IPv6

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
addons:
  - name: coredns
  - name: kube-proxy
  - name: vpc-cni

managedNodeGroups:
  - name: ng-cluster
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: true # Use default key from AWS account
      publicKeyPath: ~/.ssh/kartik_id_rsa.pub
    updateConfig:
      maxUnavailable: 2
