# Note: Update the tailscale.com/tailnet-ip annotation to match your cluster1 UDP relay IP
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  annotations:
    # TODO: Update this IP to your cluster1 UDP relay IP
    tailscale.com/tailnet-ip: 100.111.122.14
  name: udp-relay-2
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
  ports:
    - port: 8080
      protocol: TCP
      name: web
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-udp-relay-2
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    tailscale_com_managed: "true"
    tailscale_com_metrics_target: udp-relay-2
    ts_prom_job: ts_udp_relay_monitoring_udp-relay-2
    # TODO: Update parent name to match your cluster1 naming
    ts_proxy_parent_name: udp-relay-kb-cluster1-aws-uw2-sr-1-2
    ts_proxy_parent_namespace: monitoring
    ts_proxy_type: udp-relay
spec:
  staticConfigs:
  - targets:
    - udp-relay-2.monitoring.svc.cluster.local:8080
    labels:
      ts_prom_job: ts_udp_relay_monitoring_udp-relay-2
      # TODO: Update parent name to match your cluster1 naming
      ts_proxy_parent_name: udp-relay-kb-cluster1-aws-uw2-sr-1-2
      ts_proxy_parent_namespace: monitoring
      ts_proxy_type: udp-relay
      tailscale_com_managed: "true"
      tailscale_com_metrics_target: udp-relay-2
  metricsPath: /metrics
  scrapeInterval: 5s
  relabelings:
  - targetLabel: namespace
    replacement: tailscale
  - sourceLabels: [ts_prom_job]
    targetLabel: job
  - sourceLabels: [ts_proxy_parent_name]
    targetLabel: ts_proxy_parent_name
  - sourceLabels: [ts_proxy_parent_namespace]
    targetLabel: ts_proxy_parent_namespace
  - sourceLabels: [ts_proxy_type]
    targetLabel: ts_proxy_type