---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  interval: 30m
  path: ./clusters/common/apps/flux-system/notifications
  prune: true
  sourceRef:
    kind: GitRepository
    name: dogfooding-tailscale
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
