apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.80.3
    namespace: tailscale
    releaseName: tailscale-operator
    includeCRDs: true
    valuesInLine:
      oauth:
        clientId: "$TAILSCALE_OAUTH_CLIENT_ID"
        clientSecret: "$TAILSCALE_OAUTH_CLIENT_SECRET"
      apiServerProxyConfig:
        mode: "true"
      operatorConfig:
        hostname: "cluster1-aws-eastus-operator"