apiVersion: v1
kind: Service
metadata:
  name: tsdnsreflector
  labels:
    app: tsdnsreflector
spec:
  selector:
    app: tsdnsreflector
  ports:
  - port: 53
    targetPort: 5353
    protocol: UDP
    name: dns-udp
  - port: 53
    targetPort: 5353
    protocol: TCP
    name: dns-tcp
  type: ClusterIP 