apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.8.26
    namespace: argocd
    releaseName: argocd
    includeCRDs: true
    valuesFile: values.yaml
    apiVersions:
      - monitoring.coreos.com/v1