global:
  domain: argocd.lukehouge.com
configs:
  cm:
    url: https://argocd.rajsingh.info
    admin.enabled: true
    resource.ignoreResourceUpdatesEnabled: "false"
    exec.enabled: "true"
    kustomize.buildOptions: --enable-helm
    resource.exclusions: |
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - "*"
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $argocd-oidc-secret:oidc.clientID
          clientSecret: $argocd-oidc-secret:oidc.clientSecret
          orgs:
          - name: lukeandraj
  rbac: 
    policy.csv: |
      g, lukeandraj:robbinsdale, role:admin
    policy.default: role:admin
  params:
    controller.repo.server.timeout.seconds: "300"
    server.repo.server.timeout.seconds: "300"
  repositories:
    argoproj-helm:
      type: helm
      name: argo-cd
      url: https://argoproj.github.io/argo-helm
server:
  env:
    - name: ARGOCD_GRPC_KEEP_ALIVE_MIN
      value: "30s"
  extraArgs:
    - --request-timeout=300s
    - --insecure
    - --repo-server-timeout-seconds=300
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 256Mi

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 128Mi

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 1Gi

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 128Mi

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 512Mi
    limits:
      memory: 512Mi
