apiVersion: v1
kind: Service
metadata:
  name: iperf-server
  namespace: default
  labels:
    app: iperf-server
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - port: 5201
    targetPort: 5201
    protocol: TCP
    name: iperf
  selector:
    app: iperf-server 