apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsdnsreflector
  labels:
    app: tsdnsreflector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tsdnsreflector
  template:
    metadata:
      labels:
        app: tsdnsreflector
    spec:
      containers:
      - name: tsdnsreflector
        image: quay.io/rajsinghcpre/tsdnsreflector:latest
        imagePullPolicy: Always
        env:
        - name: SITE_ID
          valueFrom:
            configMapKeyRef:
              name: tsdnsreflector-config
              key: site_id
              optional: false
        - name: IPV6_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: tsdnsreflector-config
              key: ipv6_domain
              optional: false
        - name: IPV4_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: tsdnsreflector-config
              key: ipv4_domain
              optional: false
        - name: DNS_RESOLVER
          valueFrom:
            configMapKeyRef:
              name: tsdnsreflector-config
              key: dns_resolver
              optional: true
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: tsdnsreflector-config
              key: port
              optional: true
        - name: FORCE_4VIA6
          valueFrom:
            configMapKeyRef:
              name: tsdnsreflector-config
              key: force_4via6
              optional: true
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.1"
            memory: "64Mi"
        livenessProbe:
          tcpSocket:
            port: 5353
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5353
          initialDelaySeconds: 5
          periodSeconds: 10