apiVersion: v1
kind: Service
metadata:
  name: tsdnsreflector
  labels:
    app: tsdnsreflector
spec:
  selector:
    app: tsdnsreflector
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  type: ClusterIP 