apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsdnsreflector
  labels:
    app: tsdnsreflector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tsdnsreflector
  template:
    metadata:
      labels:
        app: tsdnsreflector
    spec:
      containers:
      - name: tsdnsreflector
        image: quay.io/rajsinghcpre/tsdnsreflector:latest
        imagePullPolicy: Always
        ports:
        - name: dns-udp
          containerPort: 5353
          protocol: UDP
        - name: dns-tcp
          containerPort: 5353
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        envFrom:
        - configMapRef:
            name: tsdnsreflector-config

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tsdnsreflector
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000