apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: raj-c1
  region: us-east-1
  version: "1.32"

kubernetesNetworkConfig:
  ipFamily: IPv6
vpc:
  clusterEndpoints:
    publicAccess: true

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
addons:
  - name: coredns
  - name: kube-proxy
  - name: vpc-cni

managedNodeGroups:
  - name: ng-cluster
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: true # Use default key from AWS account
      publicKeyPath: ~/.ssh/kartik_id_rsa.pub
    updateConfig:
      maxUnavailable: 2