apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster2-connector
spec:
#   proxyClass: prod 
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      - fdc0:3361:b62f::/108
      - 2600:1f18:16c8:6d00::/56
  exitNode: true