apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster2-connector
spec:
  proxyClass: prod
  hostname: kb-cluster2-aws-uw2-connector
  tags:
    - tag:k8s-operator
  subnetRouter:
    advertiseRoutes:
      - "10.41.0.0/16"