apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster2-connector
spec:
#   proxyClass: prod 
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      - fdbb:cbf8:2702::/108
      - 2600:1f18:bfd:1200::/56
  exitNode: true