apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster2-connector
spec:
  proxyClass: prod 
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      - fd7a:115c:a1e0:b1a:0:2::/96
  exitNode: true