---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tsdnsreflector-config
data:
  site_id: "4"
  ipv6_domain: "cluster4.local"
  ipv4_domain: "cluster.local"
  port: "5353"
  # Optional: custom DNS resolver in the format "host:port"
  # dns_resolver: "8.8.8.8:53" 