apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster1-connector
spec:
#   proxyClass: prod
  subnetRouter:
    advertiseRoutes:
      - fd7e:2ded:c6d2::/108
      - 2600:1f10:435c:3700::/56
  exitNode: true