apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster1-connector
spec:
#   proxyClass: prod 
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      - fdac:a172:3613::/108
      - 2600:1f18:2abc:e500::/56
  exitNode: true