apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster1-aws-eastus-connector
spec:
  proxyClass: prod 
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      # - 10.40.0.0/16
      # - 10.0.0.0/16
      - fd7a:115c:a1e0:b1a:0:2::/96
  exitNode: true