apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster3-connector
spec:
#   proxyClass: prod 
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      - fd1a:18fe:9d57::/108
      - 2600:1f10:4cb9:e000::/56
  exitNode: true