apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster3-connector
spec:
#   proxyClass: prod 
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      - fd3d:cd76:4993::/108
      - 2600:1f10:4410:1c00::/56
  exitNode: true