apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: tailscale
  name: tailscale
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tailscale
    spec:
      initContainers:
      - args:
        - sysctl -w net.ipv4.ip_forward=1 && if sysctl net.ipv6.conf.all.forwarding; then
          sysctl -w net.ipv6.conf.all.forwarding=1; fi
        command:
        - /bin/sh
        - -c
        image: tailscale/tailscale:v1.82.0
        imagePullPolicy: IfNotPresent
        name: sysctler
        resources: {}
        securityContext:
          privileged: true
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: TS_KUBE_SECRET
          value: ""
        - name: TS_USERSPACE
          value: "false"
        # - name: TS_EXTRA_ARGS
        #   value: "--accept-routes --reset"
        - name: TS_STATE_DIR
          value: /tsstate
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_ACCEPT_DNS
          value: "true"
        image: "ghcr.io/tailscale/tailscale:latest"
        imagePullPolicy: IfNotPresent
        name: tailscale
        resources: {}
        securityContext:
          privileged: false
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/tailscale
          name: var-lib-tailscale
        - mountPath: /run/tailscale
          name: run-tailscale
        - mountPath: /dev
          name: dev
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - hostPath:
          path: /dev
          type: DirectoryOrCreate
        name: dev
      - hostPath:
          path: /run/tailscale
          type: DirectoryOrCreate
        name: run-tailscale
      - hostPath:
          path: /var/lib/tailscale
          type: DirectoryOrCreate
        name: var-lib-tailscale
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate