apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster0-kind-connector
spec:
#   proxyClass: prod
  subnetRouter:
    advertiseRoutes:
      # - 10.40.0.0/16
      # - 10.0.0.0/16
      - fd7a:115c:a1e0:b1a:0:0::/96
  exitNode: true